CREATE TABLE IF NOT EXISTS WALLETS (
    ID SERIAL PRIMARY KEY,FULL_NAME VARCHAR(100), CPF BIGINT, EMAIL VARCHAR(100),
    "PASSWORD" VARCHAR(100), "TYPE" INT, BALANCE DECIMAL(10, 2)
);

CREATE UNIQUE INDEX IF NOT EXISTS cpf_idx ON WALLETS (CPF);
CREATE UNIQUE INDEX IF NOT EXISTS email_idx ON WALLETS (EMAIL);

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    ID SERIAL PRIMARY KEY,
    payer INT,
    payee INT,
    "VALUE" DECIMAL(10, 2),
    created_at TIMESTAMP, FOREIGN KEY (payer) REFERENCES WALLETS(ID), FOREIGN KEY
     (payee) REFERENCES WALLETS(ID)
);